name: Manifest

on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  contribs:
    runs-on: ubuntu-latest
    name: Manifest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          path: ncs/nrf
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          persist-credentials: false
            
    - name: Scripts
      env:
        BASE_REF: ${{ github.base_ref }}
      working-directory: ncs/nrf
      run: |
        git remote -v
        echo "Git log:"
        git log  --pretty=oneline | head -n 10
